name: Internship Monitor

on:
  workflow_dispatch:

  schedule:
    - cron: "7,22,37,52 * * * *"

permissions:
  contents: write

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run internship bot
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: python main.py

      - name: Save seen internships
        run: |
          if git diff --quiet seen_jobs.json; then
            echo "No new changes to save."
            exit 0
          fi

          git config user.name "internship-bot"
          git config user.email "internship-bot@users.noreply.github.com"

          git add seen_jobs.json
          git commit -m "Update seen internships"
          git push
